### PR TITLE
Update WI and WCR modules

### PR DESCRIPTION
**Pull request by redfrexx**

### CODE REVIEW

**Comment by j08lue** [comment]
Thanks for your contributions @redfrexx.

Merging this one is a bit problematic, because the `rlibs` are actually a separate repo (git submodule) that we currently maintain together with the modules for WOIS at https://github.com/TIGER-NET/WOIS_rlibs. Please keep this PR open and I will find a way to merge things.

**Comment by redfrexx** [comment]
I resolved all conflicts so I think merging the pull request should work now.

**Comment by j08lue** [comment]
I can see you removed the `rlibs` submodule and added a folder instead. This breaks my current setup, but that was probably not too good anyways. 

We should perhaps move the `GWAutils` to their own repository, though. I will merge now and figure out later what to do.

**Comment by j08lue** [comment]
@redfrexx do you rely on that your `rlibs/GWAutils` folder is located in `rscripts/GWA_TBX` or does it just have to be somewhere in QGIS' R paths? 

It used to be in the root of this package and thereby get installed to `~/.qgis2/processing/rlibs`.

**Comment by redfrexx** [comment]
it should be located in `~/.qgis2/processing/rlibs` Should I add it to the WOIS_rlibs repo?

**Pull request merged**
