### PR TITLE
landsat indices and RandomForestClass update from ysun

### PR DESCRIPTION
**Pull request by j08lue**
@kegro, please verify that the updates to RandomForestClass are compatible.

ysun, I changed the logic of the landsatindices files: Python module and QGIS interface in the same directory like we use [for sen2indices](https://github.com/DHI-GRAS/QGIS_sentinel_scripts/tree/master/sen2indices).

### CODE REVIEW

**Comment by j08lue** [comment]
I now also added the `sen2indices` script to this repo (https://github.com/GlobWetlandAfricaIII/GWA_scripts/pull/1/commits/432dd43e4fb6d323769d7b3348975f2c157e26f2).

I can see that you already [refer to it in the workflow](https://github.com/GlobWetlandAfricaIII/GWA_models_and_workflows/blob/0a4740948c34985536fb4409dbd6db5e36816f2d/workflows/GWA_TBX/02_Indices%20calculation%20and%20texture%20extraction.workflow#L3) as `sentinel2indiceswhm` and made sure that name matches, so there should be **no need to change the workflow**.

NB: I changed the output format to be scaled (`*1e4`) **int16 instead of float32**, as we discussed. @sun0601 does this have implications downstream, e.g. in other algorithms that use this index?

**Comment by sun0601** [comment]
Landsat indices also need to be scaled and save as int16 format. In addition, in order to use int16 format in the layer stacking before classification, the texture features also need to be scaled.

**Comment by j08lue** [comment]
Will you implement these changes, @sun0601? Then I will merge this pull request and you can perhaps create a pull request with your changes?

**Comment by kegro** [comment]
@j08lue @sun0601 We agreed to make separate scripts for the index stacks specific to each workflow.

Regarding the Random Forest classifier - the only changes that Yiwen made were to remove the progress bar and plot variable importance. If it OK with you Yiwen, we shold stick to the original script here: 

https://github.com/DHI-GRAS/gras_scripts/blob/master/Projects/GlobWetlandAfrica/R/RandomForestClass.rsx

**Comment by sun0601** [comment]
@kegro Yes, I agree that we stick to the original script.

**Comment by kegro** [comment]
OK @j08lue I've updated the Random Forest script, and the others. We should be OK now.

**Pull request merged**
